---
- name: "Prueba básica con ansible.windows"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Ping a host Windows"
      ansible.windows.win_ping:

    - name: "Mostrar mensaje"
      debug:
        msg: "Si ves este mensaje, la colección ansible.windows funciona correctamente"
